### ISSUE TITLE
Cygwin compilation

### ISSUE THREAD

**Issue by Duonijo** [georgjz/kitsune#4]
Hey good work on courses that you wrote for SNES !! 
Maybe it's my bad, but i got this :

$ make
g++ -c -fno-keep-inline-dllexport -D_GNU_SOURCE -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -Imoc_generated -Iui_generated -I/usr/lib/qt5/mkspecs/cygwin-g++ -o obj/Main.o src/Main.cpp
In file included from src/Main.cpp:23:0:
src/Kitsune.hpp:26:10: erreur fatale: QtWidgets/QMainWindow : No such file or directory
 #include <QtWidgets/QMainWindow>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminée.
make: *** [Makefile:382: obj/Main.o] Error 1

**Comment by jeffythedragonslayer** [comment]
Do you have Qt installed?

**Comment by georgjz** [comment]
I'm very sorry for my late reply. I'm closing this as I'm no longer going to work on this. The repository will be archived, if anyone wishes to port this to newer versions of Qt (and suffer through my very bad C++).
