### ISSUE TITLE
Trouble finding qmake.exe

### ISSUE THREAD

**Issue by jeffythedragonslayer** [georgjz/kitsune#5]
Hi, are you aware of instructions anywhere on how to build qmake for windows?  After installing qt-unified-windows-x86-4.1.1-online.exe I can't find it:

```
C:\Qt>where qmake.exe /R .
INFO: Could not find files for the given pattern(s).
```

**Comment by georgjz** [comment]
I'm very sorry for my late reply; I haven't touch this in ages and Qt has become a bit of a monster :P 

I'll archive the repository, but I think this will probably no longer work with newer versions of Qt.

Aseprite is better any way and there's SNES plugins for it 😄
